apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
  selector:
    app: chat